config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => 'messages#show', as: 'message'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' ,registrations: 'users/registrations'}
  root 'home#top'
  get "home/about" => "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users , only: [:show,:index,:edit,:update] do
  	member do
  		get :following
  		get :followers
  	end
  end
  resources :relationships, only: [:create, :destroy]

  get "/search" => "books#search"

  get "/search/history" => "books#history"
  post "/search/sort" => "books#sort"
  get "/search/sort" => "books#sort"

  post '/books/:book_id/favorites' => "favorites#create"
  delete '/books/:book_id/favorites' => "favorites#destroy"
  resources :books , only: [:index,:show,:create,:edit,:update,:destroy] do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",
  foreign_key: "follower_id" , dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
  foreign_key: "following_id" , dependent: :destroy

  has_many :following, through: :active_relationships, source: 
  :following
  has_many :followers, through: :passive_relationships, source: 
  :follower

  has_many :search_histories, dependent: :destroy

  has_many :user_rooms
  has_many :messages
  has_many :rooms, through: :user_rooms



  # ユーザをフォローする
  def follow(other_user)
  	following << other_user
  end

  # ユーザをフォロー解除する
  def unfollow(other_user)
  	active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザがフォローしてたらtrueを返す
  def following?(other_user)
  	following.include?(other_user)
  end

  def self.search(model,search_method,search)
    if model == "user"
      if search_method == "完全一致"
          # 〜に完全に一致する
          User.where(['name LIKE ?', "#{search}"])
        elsif search_method == "を含む"
          # 〜を含む
          User.where(['name LIKE ?', "%#{search}%"])
        elsif search_method == "から始まる"
          # 〜から始まる
          User.where(['name LIKE ?', "#{search}%"])
        elsif search_method == "で終わる"
          # 〜で終わる
          User.where(['name LIKE ?', "%#{search}"])
        end
    end
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid: auth.uid,
        provider: auth.provider,
        name: auth.info.name,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20],
      )
      user.save(:validate => false)
    end
    user
  end

  validates :name, presence: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}
# 住所自動入力
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    UserMailer.with(user: @user).welcome_email.deliver_later
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def index
  	@users = User.all
  	@book = Book.new
  end

  def search
    @book = Book.new
    @users = User.search(params[:model],params[:search_method],params[:search])
  end


  def show
  	@user = User.find(params[:id])
  	@book = Book.new
    @favorites = Favorite.where(user_id: @user.id)
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated."
  	  redirect_to user_path(@user.id)
    else
      flash[:notice] = "error"
      render :edit
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
		<div class="col-xs-3">
			<div class="profile-container">
				<h2> User info</h2>
				<h3 class="profile-name">
					<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpeg", size:'100x100' %><br>
				</h3>
				<table class="table">
					<tbody>
						<tr></tr>
						<tr>
						  <th>name</th>
						  <th><%= user.name %>
						  </th>
						</tr>
						<tr>
						  <th>introduction</th>
						  <th><%= user.introduction %></th>
						</tr>
						<tr>
						  <th>
						  	<%= link_to "following: #{current_user.following.count}", following_user_path(current_user) %>
						  </th>
						  <th>
						  	<%= link_to "followers: #{current_user.followers.count}", followers_user_path(current_user) %>
						  </th>

						</tr>
					</tbody>
				</table>
			</div>
		  <% if current_user == user %>
			<div class="row">
			    <div>
					<button type="button" class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" data-toggle="modal" data-target="#modal1"></button>
				</div>
			</div>
		  <% end %>

		  <div>
		    <% if current_user != user %>
			  <% if current_user.following?(@user) %>
				<%= form_for(current_user.active_relationships.find_by(following_id: user.id),html: {method: :delete}) do |f| %>
					<%= f.submit 'Unfollow', class: "btn btn-danger " %>
				<% end %>
			  <% else %>
				<%= form_for(current_user.active_relationships.build) do |f| %>
					<%= hidden_field_tag :following_id, user.id %>
					<%= f.submit "Follow", class: "btn btn-primary" %>
					<%= link_to 'DM', message_path(user.id),class: 'btn btn-info' %>
				<% end %>
			  <% end %>
		    <% end %>

		  </div>

			<h2 class="new-book"> New book</h2>
			  <%= form_for(book, remote: true) do |f| %>
				<h4> Title</h4>
				<%= f.text_field :title %>

				<h4> Opinion</h4>
				<%= f.text_area :body %>

				<%= f.submit 'Create Book'%>
     		  <% end %>

			</form>

		</div>

<div class="modal fade" id="modal1" tabindex="-1"
      role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label1">Edit User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <!-- モーダルの中身 -->
		<div class="container">
			<p id="notice" style="color: green;">
			<% if flash[:notice] %>
				<%= flash[:notice] %>
			<% end %>
			</p>
		　　<h2> User info</h2>

			<%= form_for(user) do |f| %>

			  <div class="field">
			    <%= f.label :name %>
			    <%= f.text_field :name, autofocus: true %>
			  </div>

			 <div class="field">
			 	<%= f.label :image %>
			 	<%= f.attachment_field :profile_image %>
			 </div>

			 <div class="field">
			 	<%= f.label :introduction %>
			 	<%= f.text_area :introduction, autofocus: true %><br />
			 </div>

			 	<%= f.submit "Update User" %>
			<% end %>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1">
  Launch demo modal
</button>
<div class="modal fade" id="modal1" tabindex="-1"
      role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label1">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
<div class="container">
	<p id="notice" style="color: green;">
	<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>
	</p>
　　<h2> User info</h2>

	<%= form_for(@user) do |f| %>

	  <div class="field">
	    <%= f.label :name %>
	    <%= f.text_field :name, autofocus: true %>
	  </div>

	 <div class="field">
	 	<%= f.label :image %>
	 	<%= f.attachment_field :profile_image %>
	 </div>

	 <div class="field">
	 	<%= f.label :introduction %>
	 	<%= f.text_area :introduction, autofocus: true %><br />
	 </div>

	 	<%= f.submit "Update User" %>
	<% end %>
</div>
        Modal body
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
	<p id="notice" style="color: green;">
	<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>
	</p>
  <div class="row">
	<%= render 'users/list', user: current_user, book: @book %>
  	<div class="col-xs-9">
	  	<h2> Users</h2>

		<table class="table table-hover table-inverse">

		  <thead>
			<tr>
			  <th>image</th>
			  <th>name</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<% @users.each do |user| %>
			<tr>
			  <td>
			    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg', size: '40x40' %><br>
			  </td>
			  <td>
			    <%= user.name %><br>
			  </td>
			  <td>
				<%= link_to "show" , user_path(user) %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>

	</div>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
	<p id="notice" style="color: green;">
	<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>
	</p>
  <div class="row">
	<%= render 'users/list', user: current_user, book: @book %>
  	<div class="col-xs-9">
	  	<h2> Users</h2>
		<h3>Search Users</h3>

		<%= form_tag(search_path,:method => 'get') do %>
		  <%= text_field_tag :search %>
		  <%= submit_tag 'Search', :name => nil %>
		<% end %>

		<h3>Search Result</h3>

		<table class="table table-hover table-inverse">

		  <thead>
			<tr>
			  <th>image</th>
			  <th>name</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<% @users.each do |user| %>
			<tr>
			  <td>
			    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg', size: '40x40' %><br>
			  </td>
			  <td>
			    <%= user.name %><br>
			  </td>
			  <td>
				<%= link_to "show" , user_path(user) %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>

	</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<p id="notice" style="color: green;">
	<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>
	</p>
  <div class="row">
	<%= render 'users/list', user: @user, book: @book, remote: true %>
  	<div class="col-xs-9">

	  <h2> Books</h2>

		<table class="table table-hover table-inverse">
		  <thead>
			<tr>
			  <th></th>
			  <th>Title</th>
			  <th>Body</th>
			</tr>
		  </thead>

		  <tbody>
			<% @user.books.each do |book| %>
			<tr>
			  <td>
				<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback:"no_image.jpeg",size:'40x40' %>
			  </td>
			  <td>
				<%=link_to book.title, book_path(book) %>
			  </td>
			  <td>
			  	<%= book.body %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>

	  <h2> Favorite Books</h2>

		<table class="table table-hover table-inverse">
		  <thead>
			<tr>
			  <th></th>
			  <th>Title</th>
			  <th>Body</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<% @favorites.each do |favorite| %>
			<% @book_id = favorite.book_id %>
			<% book = Book.find(favorite.book_id) %>
			<tr>
				  <td>
				  	<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg' %>
					<% end %>
				  </td>
				  <td>
				    <%=link_to book.title, book_path(book) %>
				  </td>
				  <td>
					<%= book.body %>
				  </td>
				  <td id="favorite-<%= book.id %>">
					<%= render partial: "books/favorite", locals: { book: book } %>
  				  </td>

			</tr>
			<% end %>
		  </tbody>

		</table>

	</div>
  </div>
</div>

app/views/users/show_follow.html.erb
<h1><%= "#{@user.name} 's following" %></h1>
<div class="container">
  <div class="row">

	<div class="col-xs-9">
		<table class="table table-hover table-inverse">

		  <thead>
			<tr>
			  <th>image</th>
			  <th>name</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
		  	<h2> Users</h2>
			<% @user.following.each do |user| %>
			<tr>
			  <td>
			    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg', size: '40x40' %><br>
			  </td>
			  <td>
			    <%= user.name %><br>
			  </td>
			  <td>
				<%= link_to "show" , user_path(user) %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>

		<%= link_to "Back", user_path(current_user) %>
	</div>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <div class="row">
	<h1><%= "#{@user.name} 's Followers" %></h1>
	<div class="col-xs-9">
		<table class="table table-hover table-inverse">

		  <thead>
			<tr>
			  <th>image</th>
			  <th>name</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
		  	<h2> Users</h2>
			<% @user.followers.each do |user| %>
			<tr>
			  <td>
			    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg', size: '40x40' %><br>
			  </td>
			  <td>
			    <%= user.name %><br>
			  </td>
			  <td>
				<%= link_to "show" , user_path(user) %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>

		<%= link_to "Back", user_path(current_user) %>
	</div>
  </div>
</div>