config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => 'messages#show', as: 'message'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' ,registrations: 'users/registrations'}
  root 'home#top'
  get "home/about" => "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users , only: [:show,:index,:edit,:update] do
  	member do
  		get :following
  		get :followers
  	end
  end
  resources :relationships, only: [:create, :destroy]

  get "/search" => "books#search"

  get "/search/history" => "books#history"
  post "/search/sort" => "books#sort"
  get "/search/sort" => "books#sort"

  post '/books/:book_id/favorites' => "favorites#create"
  delete '/books/:book_id/favorites' => "favorites#destroy"
  resources :books , only: [:index,:show,:create,:edit,:update,:destroy] do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  	end

  	def self.search(model,search_method,search)

	  	if model == "book"
	      if search_method == "完全一致"
	      	# 〜に完全に一致する
	        Book.where(['title LIKE ?', "#{search}"])
	      elsif search_method == "を含む"
	      	# 〜を含む
	        Book.where(['title LIKE ?', "%#{search}%"])
	      elsif search_method == "から始まる"
	        # 〜から始まる
	        Book.where(['title LIKE ?', "#{search}%"])
	      elsif search_method == "で終わる"
	        # 〜で終わる
	        Book.where(['title LIKE ?', "%#{search}"])
	      end
	    end
	end

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
  	@books = Book.page(params[:page]).reverse_order
  	@book = Book.new
  end

  def search
    @book = Book.new
    @books = Book.search(params[:model],params[:search_method],params[:search])
    @users = User.search(params[:model],params[:search_method],params[:search])
    new_history = current_user.search_histories.new(user_id: current_user.id,search: params[:search])
    if current_user.search_histories.exists?(search: params[:search])
      old_history = current_user.search_histories.find_by(search: params[:search])
      old_history.destroy
    end
    if params[:search] != ""
    new_history.save
    end
  end

  def history
    sort = params[:sort] || "created_at DESC"
    @histories = SearchHistory.where(user_id: current_user.id).order(sort)
  end

  def sort
    sort = params[:sort] || "created_at DESC"
    @histories = SearchHistory.where(user_id: current_user.id).order(sort)
    respond_to do |format|
    format.js {}
    end
  end

  def show
    @book_new = Book.new
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        format.js {}
      else
        @books = Book.page(params[:page]).reverse_order
        format.html { render :index }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "Book was successfully updated."
    	redirect_to book_path(@book)
    else
      render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	if book.destroy
  		flash[:notice] = "Book was successfully destroyed."
  	end
  	redirect_to user_path(current_user)
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>
  <td>
  	<%= link_to user_path(book.user_id) do %>
		<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg' %>
	<% end %>
  </td>
  <td>
    <%=link_to book.title, book_path(book) %>
  </td>
  <td>
	<%= book.body %>
  </td>
  <td id="favorite-<%= book.id %>">
	<%= render partial: "favorite", locals: { book: book } %>
  </td>
</tr>

app/views/books/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, book_id: book.id) %>
  <%= link_to "/books/#{book.id}/favorites", method: :delete, remote: true do %>
	<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
  <% end %>
<% else %>
  <%= link_to "/books/#{book.id}/favorites", method: :post, remote: true do %>
  	<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    <% end %>
<% end %>
<%= book.favorites.count %> いいね

app/views/books/_sort.html.erb
<% @histories.each do |history| %>
<tr>
  <td>
	<%= history.search %>
  </td>
  <td>
	<%= history.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
<% end %>

app/views/books/create.js.erb
$("<%= escape_javascript(render @book) %>").prependTo("#books");

app/views/books/edit.html.erb
<div class="container">
	<div id="alert alert-danger">
				<% if @book.errors.any? %>
        			<h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
        			<ul>
        			<% @book.errors.full_messages.each do |message| %>
            			<li><%= message %></li>
        			<% end %>
        		    </ul>
    			<% end %>
    </div>
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">
		<h1> Editing Book</h1>

		  <%= form_for(@book) do |f| %>

			<div class="field row">
			  <label for="book_title">Title</label><br>
				<%= f.text_field :title, class: "col-xs-12 book_title" %>
			</div>

			<div class="field row">
			  <label for="book_body">Opinion</label><br>
				<%= f.text_area :body, class: "col-xs-12 book_body" %><br>
			</div>

			<div class="actions row" style="margin-top: 10px;"">
				<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %></br>

		  <% end %>

		<%= link_to 'Show', book_path(@book) %> | 
		<%= link_to 'Back', books_path %>

</div>

app/views/books/history.html.erb
<h3> Search History </h3>
<table class="table table-hover table-inverse">

  <thead>
	<tr>
	  <th>SeachWord</th>
	  <th>
	  	  <%= form_tag(search_sort_path,:method => 'get',remote: true) do %>
          <%= select_tag :sort, options_for_select(["search asc","search desc", "created_at asc", "created_at desc"]) %>
          <%= submit_tag '並べ替え', :name => nil %>
          <% end %>
	  </th>
	</tr>
  </thead>

  <tbody>
	<%= render 'books/sort' %>
  </tbody>

</table>

app/views/books/index.html.erb
<div class="container">
	<div id="alert alert-danger">
				<% if @book.errors.any? %>
        			<h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
        			<ul>
        			<% @book.errors.full_messages.each do |message| %>
            			<li><%= message %></li>
        			<% end %>
        		    </ul>
    			<% end %>
    </div>

	<div class="row">

		<%= render 'users/list', user: current_user, book: @book %>

		<div class="col-xs-9">

			<h2>Books</h2>

			<table class="table table-hover table-inverse">
			<tbody id="books">
			    <%= render @books %>
		    </tbody>
			</table>
			    <%= paginate @books, class: "paginate" %>

		</div>
	</div>
</div>

app/views/books/search.html.erb
<div class="container">
	<div id="alert alert-danger">
				<% if @book.errors.any? %>
        			<h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
        			<ul>
        			<% @book.errors.full_messages.each do |message| %>
            			<li><%= message %></li>
        			<% end %>
        		    </ul>
    			<% end %>
    </div>


<% if params[:model] == "book" %>
	<div class="row">

		<%= render 'users/list', user: current_user, book: @book %>

		<div class="col-xs-9">

			<h2>Books</h2>

			<h3>Search Result</h3>

			<table class="table table-hover table-inverse">
			  <thead>
				<tr>
				  <th></th>
				  <th>Title</th>
				  <th>Body</th>
				  <th></th>
				</tr>
			  </thead>

			  <tbody>
				<% @books.each do |book| %>
				<tr>
				  <td>
				  	<%= link_to user_path(book.user_id) do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg' %>
					<% end %>
				  </td>
				  <td>
				    <%=link_to book.title, book_path(book) %>
				  </td>
				  <td>
					<%= book.body %>
				  </td>
				  <td id="favorite-<%= book.id %>">
					<%= render partial: "favorite", locals: { book: book } %>
  				  </td>
				</tr>
				<% end %>
			  </tbody>

			</table>
<% else %>

<div class="row">
	<%= render 'users/list', user: current_user, book: @book %>
  	<div class="col-xs-9">
	  	<h2> Users</h2>

		<h3>Search Result</h3>

		<table class="table table-hover table-inverse">

		  <thead>
			<tr>
			  <th>image</th>
			  <th>name</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<% @users.each do |user| %>
			<tr>
			  <td>
			    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: 'no_image.jpeg', size: '40x40' %><br>
			  </td>
			  <td>
			    <%= user.name %><br>
			  </td>
			  <td>
				<%= link_to "show" , user_path(user) %>
			  </td>
			</tr>
			<% end %>
		  </tbody>

		</table>
<% end %>

		<%= link_to "検索履歴", search_history_path %>

	</div>
  </div>
</div>

app/views/books/show.html.erb
	<div class="container">
		<p id="notice" style="color: green;">
		  <% if flash[:notice] %>
			<%= flash[:notice] %>
		  <% end %>
		</p>
		<%= render 'users/list', user: @book.user, book: @book_new %>

		<div class="col-xs-9">

		  	<h2>Book detail</h2>

			<table class="table table-hover table-inverse">

				  <tbody>
					<tr>
					  <td>
					  	<%= link_to user_path(@book.user) do %>
						<%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg' ,fallback: "no_image.jpeg", size:'40x40'%><br>
						<%= @book.user.name %>
						<% end %>
					  </td>
					  <td>
					    <%= link_to @book.title, book_path(@book) %>
					  </td>
					  <td>
						<%= @book.body %>
					  </td>
					  <%if current_user == @book.user %>
						  <td>
						  	<%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book" %>
						  </td>
						  <td>
						  	<%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger destroy_book"%>
						  </td>
					  <% end %>
						    <td id="favorite-<%= @book.id %>">
								<%= render partial: "favorite", locals: { book: @book } %>
  							</td>

					</tr>
				  </tbody>
			</table>

			<h2> Comments</h2>

			<table class="table table-hover table-inverse">

				  <tbody>
				  	<% @book.book_comments.each do |book_comment| %>
				  	
				  	<tr>
				  	  <td>
				  	  	<%= link_to user_path(book_comment.user) do %>
						<%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg' %><br>
				  	  	<%= book_comment.user.name %>
						<% end %>
				  	  </td>
				  	  <td>
				  		<%= book_comment.created_at.strftime('%Y/%m/%d') %>
				  	  </td>
				  	  <td>
				  	  	<%= book_comment.comment %>
				  	  </td>
				  	  <%if current_user == book_comment.user %>
						  <td>
						  	<%= link_to "Edit", edit_book_book_comment_path(@book,book_comment), class: "btn-sm btn-success edit_book" %>
						  </td>
						  <td>
						  	<%= link_to "Destroy", book_book_comment_path(@book,book_comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger destroy_book"%>
						  </td>
					  <% end %>
				  	</tr>

				  	<% end %>

				  </tbody>

			</table>

			<h2> Post Comment</h2>

			<%= form_for [@book, @book_comment] do |f| %>

				<h4> Comment</h4>
				<%= f.text_area :comment %><br>
				<%= f.submit "Create Comment" %>

			<% end %>

		</div>
	</div>

app/views/books/sort.js.erb
$("tbody").html("");
$("tbody").html("<%= escape_javascript(render 'sort') %>");