config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => 'messages#show', as: 'message'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' ,registrations: 'users/registrations'}
  root 'home#top'
  get "home/about" => "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users , only: [:show,:index,:edit,:update] do
  	member do
  		get :following
  		get :followers
  	end
  end
  resources :relationships, only: [:create, :destroy]

  get "/search" => "books#search"

  get "/search/history" => "books#history"
  post "/search/sort" => "books#sort"
  get "/search/sort" => "books#sort"

  post '/books/:book_id/favorites' => "favorites#create"
  delete '/books/:book_id/favorites' => "favorites#destroy"
  resources :books , only: [:index,:show,:create,:edit,:update,:destroy] do
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css"></style>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container" style="height: 90px;">
          <nav class="nav navbar-nav navbar-left">
            <span style="color: #FFFFFF; font-size: 20px;">Bookers</span>
          </nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">

              <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user),class: 'glyphicon glyphicon-home' %>
              </li>
              <li>
                <%= link_to " Users", users_path, class: 'glyphicon glyphicon-user' %>

              </li>
              <li>
                <%= link_to " Books", books_path, class: 'glyphicon glyphicon-book' %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out' %>
              </li>

              <span>
                  <%= form_tag(search_path,:method => 'get') do %>
                  <%= text_field_tag :search %>
                  <%= select_tag :model, options_for_select([:book,:user]) %>
                  <%= select_tag :search_method, options_for_select(["完全一致","を含む", "から始まる", "で終わる"]) %>
                  <%= submit_tag 'Search', :name => nil %>
                  <% end %>
              </span> 


              <% else %>
              <li>
                <%= link_to " Home", root_path, class: 'glyphicon glyphicon-home' %>
              </li>
              <li>
                <%= link_to " About", home_about_path, class: 'glyphicon glyphicon-link' %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: 'glyphicon glyphicon-edit' %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: 'glyphicon glyphicon-log-in' %>
              </li>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>

    <div class="body" style="margin-top: 100px;">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>